import type { DesignStory, FeaturePolicyDesign, MockAction, WorkbenchState } from "@/workbench/types"

type StoryOptions = {
  actions?: MockAction[]
  surface?: string | null
  status?: DesignStory["status"]
}

function story(
  id: string,
  title: string,
  userIntent: string,
  agentIntent: string,
  behavior: string,
  ownerMessage: string,
  corpusMessage: string,
  options: StoryOptions = {},
): DesignStory {
  return {
    id,
    title,
    userIntent,
    agentIntent,
    story: behavior,
    messages: [
      { id: `${id}-owner`, actor: "Owner", content: ownerMessage },
      { id: `${id}-corpus`, actor: "Corpus", content: corpusMessage },
    ],
    actions: options.actions ?? [],
    mockSurfacePath: options.surface ?? null,
    status: options.status ?? "draft",
    rejectionReason: "",
  }
}

function policies(
  nodeId: string,
  nodeTitle: string,
  featurePolicies: string[],
  nodePolicies: string[] = [],
): FeaturePolicyDesign {
  return {
    policies: featurePolicies,
    nodes: [{
      id: nodeId,
      title: nodeTitle,
      policies: nodePolicies,
      capabilities: [],
      activeSurface: null,
      operations: [],
    }],
  }
}

export function createSeedState(): WorkbenchState {
  return {
    version: 10,
    features: [
      {
        id: "lounge",
        name: "Lounge",
        policies: policies(
          "lounge.home",
          "Lounge",
          ["Keep unauthenticated help general and never expose private Workspace state."],
          ["Offer product help and account access without implying that the visitor is authenticated."],
        ),
        stories: [
          story(
            "lounge-arrival",
            "Arrive in the Lounge",
            "Understand where I am and what I can do before signing in.",
            "Establish the public Lounge and keep every valid public or account path available.",
            "An unauthenticated visitor opens Corpus. Corpus places them in the Lounge, explains that it is the public starting point, and offers product help, sign-up, sign-in, and password-recovery paths without exposing private Workspace state.",
            "What can I do here?",
            "You are in the Lounge. Ask me about Corpus, sign up, sign in, or recover your password when you are ready.",
            { actions: [
              { id: "lounge-ask-product", label: "Ask about Corpus" },
              { id: "lounge-sign-up", label: "Sign up" },
              { id: "lounge-sign-in", label: "Sign in" },
              { id: "lounge-forgot-password", label: "Forgot password" },
            ] },
          ),
          story(
            "lounge-product-help",
            "Ask Lounge for product help",
            "Understand Corpus, its features, or how to get started.",
            "Answer product questions truthfully and identify when the requested work requires a Workspace.",
            "A visitor asks a general question about Corpus. Corpus answers from current product knowledge, can explain features and next steps, and clearly says when private Workspace access is required. Unknown or unavailable information remains explicit.",
            "How does Corpus help me build an agent?",
            "Corpus helps you connect sources, design behavior, test, evaluate, deploy, and operate an agent. You will need an account when you want to create private Workspace resources.",
          ),
          story(
            "owner-auth-register",
            "Create an owner account",
            "Create an account and enter my private Workspace.",
            "Create the owner identity and continue into the owner's Workspace without overstating partial success.",
            "A Lounge visitor signs up with the required account details. Corpus creates the owner account and personal Workspace, signs the owner in, and enters Workspace. If account creation succeeds but continuation fails, Corpus keeps the authenticated state valid and reports the continuation failure.",
            "I want to create an account.",
            "Sign up here. When account creation completes, I will take you into your Workspace.",
            { actions: [{ id: "register-submit", label: "Sign up" }], surface: "/mock-surfaces/workspace/authentication.html#register", status: "approved" },
          ),
          story(
            "owner-auth-sign-in",
            "Sign in",
            "Return to the private Workspace associated with my account.",
            "Authenticate the owner and resume only the Workspace authorized for that account.",
            "An existing owner signs in from Lounge with email and password. Corpus resumes only that owner's Workspace. Invalid credentials remain a visible failure and do not open private state.",
            "I already have a Corpus account.",
            "Sign in to resume the Workspace associated with your account.",
            { actions: [{ id: "sign-in-submit", label: "Sign in" }], surface: "/mock-surfaces/workspace/authentication.html#sign-in", status: "approved" },
          ),
          story(
            "owner-auth-request-reset",
            "Request password recovery",
            "Regain access because I cannot use my current password.",
            "Accept a reset request without revealing whether the account exists and report delivery failures truthfully.",
            "A visitor submits an email for password recovery. Corpus shows the same generic confirmation whether or not the account exists. When an account exists, delivery is requested; unavailable delivery remains an explicit failure.",
            "I forgot my password.",
            "Enter your email to request recovery. The confirmation will not reveal whether an account exists.",
            { actions: [{ id: "request-reset-submit", label: "Send recovery link" }], surface: "/mock-surfaces/workspace/authentication.html#request-reset", status: "approved" },
          ),
          story(
            "owner-auth-confirm-reset",
            "Set a new password",
            "Replace my password with a valid one-time recovery link.",
            "Validate the link, change the password, revoke existing access, and return the owner to sign-in.",
            "An owner opens a one-time reset link and chooses a new password. Corpus removes the token from the visible URL, changes the password, revokes existing sessions, and returns to sign-in. Missing, invalid, or expired links remain explicit failures.",
            "Use this recovery link and change my password.",
            "Choose a new password. Completing this will sign out existing sessions and return you to sign-in.",
            { actions: [{ id: "confirm-reset-submit", label: "Set new password" }], surface: "/mock-surfaces/workspace/authentication.html#reset-password", status: "approved" },
          ),
          story(
            "owner-auth-request-verification",
            "Resend email verification",
            "Receive a fresh verification email for my signed-in account.",
            "Request a new verification message and report whether delivery succeeded or is unavailable.",
            "A signed-in owner whose email is pending verification asks for another verification message. Corpus requests delivery and reports the actual result without blocking permitted Workspace use.",
            "Send the verification email again.",
            "I will request a fresh verification message and report whether delivery succeeds.",
            { actions: [{ id: "resend-verification", label: "Resend verification" }], surface: "/mock-surfaces/workspace/authentication.html#verification-pending", status: "approved" },
          ),
          story(
            "owner-auth-confirm-verification",
            "Confirm email verification",
            "Confirm that the email address belongs to my owner account.",
            "Validate the one-time link, refresh owner state, and show confirmation or an explicit token failure.",
            "An owner opens a one-time verification link. Corpus removes its token from the visible URL, verifies the address, refreshes owner state, and shows the result. Missing, invalid, or expired links remain explicit failures.",
            "Verify this email address.",
            "I will validate the one-time link and show the verification result.",
            { actions: [{ id: "confirm-verification", label: "Verify email" }], surface: "/mock-surfaces/workspace/authentication.html#verify-email", status: "approved" },
          ),
        ],
      },
      {
        id: "workspace",
        name: "Workspace",
        policies: policies(
          "workspace.home",
          "Workspace home",
          ["Use only the authenticated owner's authorized Workspace context."],
          ["Keep Workspace home oriented toward overview, navigation, and continuation; do not edit domain records here."],
        ),
        stories: [
          story(
            "enter-workspace",
            "Enter the Workspace",
            "See the current state of my private Workspace and choose what to do next.",
            "Establish the authenticated Workspace and provide a truthful overview of agents, sources, and activity.",
            "An authenticated owner enters their one launch Workspace. Corpus shows its agents, sources, and recent activity, including honest empty states. Workspace home does not add or modify domain records.",
            "Show me my Workspace.",
            "Here is the current overview of your agents, sources, and recent activity.",
          ),
          story(
            "workspace-activity-help",
            "Ask about Workspace activity",
            "Understand what exists or recently happened in my Workspace.",
            "Answer from authorized Workspace state and distinguish current facts from unavailable information.",
            "The owner asks about agents, sources, activity, or another Workspace fact. Corpus answers from the owner's authorized Workspace state and links the answer to the relevant feature when deeper inspection is useful.",
            "What changed in my Workspace today?",
            "I will summarize the activity visible in this Workspace and point you to the affected resources.",
          ),
          story(
            "workspace-product-help",
            "Ask about Corpus while signed in",
            "Get general product guidance without leaving my Workspace context.",
            "Answer the product question while preserving the authenticated Workspace as active context.",
            "An authenticated owner asks how Corpus or one of its features works. Corpus answers without discarding the current Workspace context and makes any relevant next action available.",
            "How do evaluations relate to an agent version?",
            "Evaluations run against an exact version and retain evidence. I can take you to Evaluation when you want to inspect or start one.",
          ),
          story(
            "workspace-route-task",
            "Continue a task in the correct feature",
            "Ask for any Corpus task and continue it where that work is owned.",
            "Recognize the owning feature, navigate there, and continue the same conversation without treating navigation as completion.",
            "The owner asks Workspace to perform a task owned elsewhere. Corpus navigates to the correct feature and continues the same conversation with the context needed for that task. Arrival at the feature is not presented as task completion.",
            "Attach the Orders API to my support agent.",
            "That work belongs with the agent's sources. I will open the relevant path and continue with the attachment choices there.",
          ),
          story(
            "workspace-quick-actions",
            "Use Workspace quick actions",
            "Move directly to a common area of my Workspace.",
            "Expose valid high-frequency destinations and navigate without modifying domain state.",
            "Workspace home presents quick actions for common destinations such as Agents, Sources, and Operations. Choosing one opens that feature; the quick action itself does not create or change a resource.",
            "I want to manage my agents.",
            "I will open Agents. Nothing changes until you choose an action there.",
            { actions: [
              { id: "workspace-manage-agents", label: "Manage agents" },
              { id: "workspace-manage-sources", label: "Manage sources" },
              { id: "workspace-manage-operations", label: "Manage operations" },
            ] },
          ),
          story(
            "owner-auth-sign-out",
            "Sign out to Lounge",
            "End access to my Workspace on this browser while keeping it private.",
            "Revoke current browser access and return to a fresh public Lounge without changing Workspace ownership.",
            "An authenticated owner signs out. Corpus revokes the browser session and owner route handle, clears browser credentials, and returns to a fresh Lounge. The Workspace and its resources remain private.",
            "Sign me out on this browser.",
            "I will end this browser session and return you to the Lounge. Your Workspace remains private.",
            { actions: [{ id: "sign-out", label: "Sign out" }], surface: "/mock-surfaces/workspace/authentication.html#sign-out", status: "approved" },
          ),
        ],
      },
      {
        id: "agents",
        name: "Agents",
        policies: policies(
          "agents.home",
          "Agents",
          ["Keep every agent isolated to the authenticated owner's Workspace."],
          ["Never describe an agent as runnable or deployed unless a corresponding version and deployment exist."],
        ),
        stories: [
          story(
            "agents-view",
            "View agents",
            "See the agents in my Workspace and their current lifecycle state.",
            "List only authorized agents with truthful status and useful next actions.",
            "The owner opens Agents. Corpus lists the Workspace's agents with enough identity and lifecycle information to distinguish them, including honest empty state and no implied deployment.",
            "Show me my agents.",
            "Here are the agents in this Workspace and the current state of each one.",
            { actions: [{ id: "agents-create", label: "Create agent" }] },
          ),
          story(
            "agents-create",
            "Create an agent",
            "Create an agent with a name, description, and goal.",
            "Collect the required identity fields, create the agent, and show the newly created agent without implying it is runnable or deployed.",
            "The owner provides an agent name, description, and goal. Corpus validates the required information, creates the agent in the Workspace, and opens it for inspection. Creating the agent does not create a runnable version or deployment.",
            "Create an agent for handling customer order questions.",
            "Provide its name, description, and goal. I will create the agent and then open it for you.",
            { actions: [{ id: "agents-create-confirm", label: "Create agent" }], surface: "/mock-surfaces/agents/create-agent.html" },
          ),
          story(
            "agents-inspect",
            "Inspect an agent",
            "Understand an agent's identity, configuration, sources, versions, and deployment state.",
            "Present the complete agent record and clearly distinguish configured, runnable, and deployed state.",
            "The owner opens an agent. Corpus brings together its identity, goals and non-goals, configuration inputs, attached sources, Agent Designer and RouteDeck configuration, runnable and deployed versions, and active deployment URL when one exists.",
            "Show me everything that defines this agent.",
            "I will show its identity, goals, configuration, sources, versions, and active deployment state in one place.",
          ),
          story(
            "agents-edit",
            "Edit an agent",
            "Change the agent's editable identity or configuration inputs.",
            "Validate and persist allowed edits while keeping versioned and deployed state truthful.",
            "The owner edits allowed agent fields such as name, description, goal, non-goals, or configuration inputs. Corpus shows what will change, saves valid edits, and does not silently rewrite existing runnable or deployed versions.",
            "Change this agent's goal to include order-status questions.",
            "I will update the agent's goal and keep existing version and deployment history distinct.",
            { actions: [{ id: "agents-save", label: "Save changes" }] },
          ),
          story(
            "agents-attach-source",
            "Attach an existing source",
            "Give this agent access to a source already in my Workspace.",
            "Present eligible sources, attach the selected source, and return to the agent with visible confirmation.",
            "The owner chooses to add a source to an agent and selects an existing Workspace source. Corpus attaches it once, returns to the agent, and shows the source in the agent's source list.",
            "Attach the Orders API source.",
            "I will attach that existing Workspace source and return to this agent.",
            { actions: [{ id: "agents-attach-existing", label: "Attach source" }] },
          ),
          story(
            "agents-create-source",
            "Create and attach a source",
            "Add a new source while working on an agent and return with it attached.",
            "Hand off to Source Hub, preserve the agent context, and attach the completed source on return.",
            "The owner chooses to add a source that does not yet exist. Corpus opens Source Hub in the context of the current agent. When source creation completes, Corpus returns to the agent and shows the new source attached; cancellation returns without attachment.",
            "This source is not in my Workspace yet.",
            "I will take you to Source Hub and return here with the completed source attached.",
            { actions: [{ id: "agents-create-source", label: "Add new source" }] },
          ),
          story(
            "agents-open-source",
            "Open an attached source",
            "Inspect or edit a source attached to this agent.",
            "Navigate to the source owner while preserving enough context to return to the agent.",
            "The owner selects an attached source for inspection or editing. Corpus navigates to that source in its owning feature and preserves the agent context for return. The Agents feature does not edit source-owned records itself.",
            "Open the Orders API source.",
            "I will open that source in its owning feature and keep this agent as the return context.",
          ),
          story(
            "agents-archive",
            "Archive an agent",
            "Remove an agent from my active working list without calling it deleted.",
            "Confirm the archive action, apply it to the selected agent, and show the resulting active-list state.",
            "The owner archives an agent after confirming the selected target. Corpus removes it from the active agent list and preserves a truthful distinction between archived and deleted state.",
            "Archive this agent.",
            "Confirm the agent you want to archive. It will leave the active list but will not be described as deleted.",
            { actions: [{ id: "agents-archive-confirm", label: "Archive agent" }] },
          ),
          story(
            "agents-delete",
            "Delete an agent",
            "Permanently remove an agent when it is safe and intended.",
            "Expose material dependencies, require confirmation, and either delete the exact agent or report blockers.",
            "The owner requests deletion. Corpus identifies the exact agent and any active deployment or other blockers before confirmation. It deletes only when permitted and visibly reports blocked or failed deletion without pretending success.",
            "Delete this agent permanently.",
            "I will check its dependencies and ask you to confirm the exact agent before permanent deletion.",
            { actions: [{ id: "agents-delete-confirm", label: "Delete permanently" }] },
          ),
        ],
      },
      {
        id: "source-hub",
        name: "Source Hub",
        policies: policies(
          "sources.home",
          "Source Hub",
          ["Expose only sources owned by the authenticated Workspace."],
          ["At launch, offer API sources only; do not imply database, knowledge, or MCP support."],
        ),
        stories: [
          story(
            "sources-view",
            "View sources",
            "See the sources in my Workspace and which agents use them.",
            "List authorized sources with truthful type, status, and attachment context.",
            "The owner opens Source Hub. Corpus lists Workspace sources, their type and readiness, and the agents to which they are attached. At launch, API is the only available source family.",
            "Show me my sources.",
            "Here are your Workspace sources, their readiness, and their agent attachments.",
            { actions: [{ id: "sources-add-api", label: "Add API source" }] },
          ),
          story(
            "sources-start-api",
            "Start adding an API source",
            "Create a new API source from the one allowed launch entry point.",
            "Open API Source from Source Hub and preserve any calling-agent context.",
            "The owner chooses Add API source in Source Hub. Corpus opens API Source, the only launch source type, and carries forward the current agent context when the flow began from an attachment task.",
            "Add an API source.",
            "I will open API Source and keep your current attachment context if you arrived from an agent.",
            { actions: [{ id: "sources-open-api", label: "Add API source" }] },
          ),
          story(
            "sources-select-for-agent",
            "Select a source for an agent",
            "Choose an existing source and return to the agent with it attached.",
            "Show eligible sources, attach the selected one, and complete the handoff back to Agents.",
            "Source Hub is opened from an agent attachment task. The owner selects an eligible source. Corpus attaches it, returns to the originating agent, and shows the completed attachment.",
            "Use the Orders API for this agent.",
            "I will attach it and return to the agent that started this task.",
            { actions: [{ id: "sources-select", label: "Select source" }] },
          ),
          story(
            "sources-delete",
            "Delete an API source",
            "Remove an API source when its dependencies allow deletion.",
            "Show agent attachments and other blockers, require confirmation, and report the actual result.",
            "The owner requests deletion of an API source. Corpus shows attached agents or other material blockers before confirmation. It deletes only when permitted and keeps blocked or failed deletion visible.",
            "Delete this API source.",
            "I will show where it is used and ask for confirmation before deleting it.",
            { actions: [{ id: "sources-delete-confirm", label: "Delete source" }] },
          ),
          story(
            "sources-start-description",
            "Start adding an API description",
            "Provide helpful Markdown context for an API source.",
            "Open the selected API Source at its description input and preserve Source Hub context.",
            "The owner chooses to add a helpful Markdown description to an API source. Source Hub opens that source's API-specific description path, where file limits, validation, and persistence are owned, and returns to the source list afterward.",
            "Add a Markdown description to the Orders API.",
            "I will open that API source at its description input and return here when it is saved.",
            { actions: [{ id: "sources-add-description", label: "Add API description" }] },
          ),
        ],
      },
      {
        id: "api-source",
        name: "API Source",
        policies: policies(
          "api-source.manage",
          "API Source",
          ["Keep API specifications, credentials, artifacts, and processing isolated to the authenticated Workspace."],
          ["Enter API Source only from Source Hub and keep processing failures explicit."],
        ),
        stories: [
          story(
            "api-upload-yaml",
            "Upload an API YAML file",
            "Create or revise an API source from an OpenAPI YAML file.",
            "Validate the file and size limits, persist an accepted revision, and report invalid input clearly.",
            "The owner uploads an OpenAPI YAML file from API Source. Corpus enforces the documented file limits and format, creates the source revision only when accepted, and shows validation failures without substituting sample data.",
            "Upload this OpenAPI YAML file.",
            "I will validate the file and create a source revision only if it is accepted.",
            { actions: [{ id: "api-upload", label: "Upload YAML" }] },
          ),
          story(
            "api-description",
            "Add or update the API description",
            "Give Corpus helpful Markdown context about how this API should be understood.",
            "Validate the Markdown file and save it to the selected API source without treating it as an API specification.",
            "The owner uploads a Markdown file that explains the API's purpose and usage. Corpus enforces explicit file limits, saves valid description content with the API source, and keeps invalid or failed uploads visible.",
            "Use this Markdown file to explain the Orders API.",
            "I will validate it as descriptive context and keep it separate from the OpenAPI specification.",
            { actions: [{ id: "api-description-upload", label: "Upload Markdown" }] },
          ),
          story(
            "api-configure-connection",
            "Configure the API connection",
            "Provide the base URL, authentication, and environment details needed to use this API.",
            "Collect non-secret configuration and private credentials safely, validate required fields, and report connection failures explicitly.",
            "The owner configures an environment or profile, base URL, authentication method, and required credentials. Corpus keeps secrets private, shows what will be used, and can perform an explicitly requested safe connection check. A failed check remains a failure.",
            "Configure the production base URL and API-key authentication.",
            "I will keep the credential private, show the non-secret connection settings, and only run a safe check when you request it.",
            { actions: [{ id: "api-save-connection", label: "Save connection" }, { id: "api-test-connection", label: "Test connection" }] },
          ),
          story(
            "api-process-toolrouter",
            "Process the API through ToolRouter",
            "Turn the accepted API revision into a semantic graph and operation inventory.",
            "Run the real ToolRouter pipeline for the exact revision and make success or failure visible.",
            "The owner starts processing for an accepted API revision. Corpus invokes ToolRouter for that exact revision, records its actual artifacts, and marks the revision ready only after required processing completes. Missing dependencies or processing errors remain failures.",
            "Process this API source.",
            "I will run ToolRouter against this exact revision and report each completed phase or failure.",
            { actions: [{ id: "api-process", label: "Process API" }] },
          ),
          story(
            "api-monitor-processing",
            "Monitor API processing",
            "Understand what ToolRouter is doing and whether the source is ready.",
            "Expose real processing phases, current status, and actionable failure details without inventing progress.",
            "While processing is active or after it ends, Corpus shows the known phase and status for the selected revision. Completed, failed, and ready states are distinct; no synthetic progress or success is shown.",
            "What is happening with this API?",
            "I will show the latest recorded processing phase and the exact failure if processing stopped.",
          ),
          story(
            "api-inspect-graph",
            "Inspect the semantic graph",
            "Understand the structure ToolRouter produced for this API revision.",
            "Present the persisted graph with enough context to inspect nodes, edges, and their source revision.",
            "After processing succeeds, the owner opens the semantic graph for the exact API revision. Corpus shows the persisted nodes and relationships and keeps the source revision identifiable.",
            "Show me the semantic graph.",
            "I will open the graph produced for this revision and keep every node tied to its source evidence.",
          ),
          story(
            "api-replay-graph",
            "Replay graph construction",
            "See how ToolRouter built the graph node by node.",
            "Replay the persisted construction trace in order without claiming live streaming that is not available.",
            "After graph processing completes, the owner replays the persisted graph-construction trace node by node. Corpus supports pause, resume, and step-through over recorded events. This baseline does not claim that construction streams live while ToolRouter is still running.",
            "Show me how this graph was built.",
            "I will replay the recorded construction events in order, one node at a time.",
            { actions: [{ id: "api-replay-start", label: "Replay construction" }, { id: "api-replay-step", label: "Step" }] },
          ),
          story(
            "api-curate-operations",
            "Curate API operations",
            "Choose which discovered API operations should be available for agent design.",
            "Present exact discovered operations and persist the owner's inclusion decisions for the source revision.",
            "The owner reviews operations discovered from the processed API revision and includes or excludes exact operations for downstream Agent Designer use. Corpus does not invent operations or silently broaden the selection.",
            "Only include order lookup and shipment tracking.",
            "I will keep those exact discovered operations and exclude the others from downstream agent design.",
            { actions: [{ id: "api-save-operations", label: "Save operation selection" }] },
          ),
          story(
            "api-recover-processing",
            "Recover from API processing failure",
            "Correct a failed API source and retry without losing the failure evidence.",
            "Keep the failed result visible, identify valid corrective actions, and retry only when the owner requests it.",
            "When upload, configuration, or ToolRouter processing fails, Corpus shows the failure and retains its evidence. The owner can correct the relevant input and explicitly retry the affected step. Corpus never substitutes a mock graph, cached success, or alternate processor.",
            "Fix the base URL and retry processing.",
            "I will save the corrected input and retry only the failed processing step when you confirm.",
            { actions: [{ id: "api-retry", label: "Retry processing" }] },
          ),
        ],
      },
    ],
  }
}
